import React from "react";
import { Sheet } from "@mui/joy";
import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
import Header from "./header/Header";
import DocuSidebar from "./docuSidebar/DocuSidebar";

function Main() {
    const [url, setUrl] = React.useState<string>(
        "https://docusaurus.io/docs/sidebar/autogenerated"
    );

    return (
        <PanelGroup direction="horizontal">
            <Panel
                defaultSize={15}
                minSize={10}
                maxSize={40}
                order={1}
                // eslint-disable-next-line react/jsx-boolean-value
                collapsible={true}
            >
                <DocuSidebar />
            </Panel>
            <PanelResizeHandle className="bg-neutral-800 w-[2px]" />
            <Panel order={2}>
                <Header />
                <Sheet
                    variant="soft"
                    sx={{
                        height: "100%",
                    }}
                >
                    <PanelGroup direction="horizontal">
                        <Panel
                            defaultSize={50}
                            minSize={20}
                            maxSize={80}
                            order={1}
                        >
                            <div className="p-6 flex flex-col gap-4">
                                <button
                                    type="button"
                                    onClick={() => {
                                        setUrl(
                                            "https://docusaurus.io/docs/sidebar/items"
                                        );
                                    }}
                                >
                                    1
                                </button>
                                <button
                                    type="button"
                                    onClick={() => {
                                        setUrl(
                                            "https://docusaurus.io/docs/sidebar/autogenerated"
                                        );
                                    }}
                                >
                                    2
                                </button>
                                <button
                                    type="button"
                                    onClick={() => {
                                        setUrl(
                                            "https://docusaurus.io/docs/sidebar/multiple-sidebars"
                                        );
                                    }}
                                >
                                    3
                                </button>
                            </div>
                        </Panel>
                        <PanelResizeHandle className="bg-neutral-700 w-1 hover:w-4" />
                        <Panel
                            order={2}
                            defaultSize={50}
                            minSize={20}
                            maxSize={80}
                            className="p-2"
                        >
                            {/* make a webview that is only readable, does not respond to anything */}
                            <webview
                                src={url}
                                style={{
                                    height: "100%",
                                    width: "100%",
                                }}
                                onClick={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                }}
                            />
                        </Panel>
                    </PanelGroup>
                </Sheet>
            </Panel>
        </PanelGroup>
    );
}

export default Main;
